version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - /app
    working_dir: /app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  postgres_data:
